version: "3.6"

volumes:
  bundle:

services:
  gem:
    build: .
    volumes:
      - .:/workspace
      - bundle:/usr/local/bundle
      - $HOME/.ssh:/root/.ssh:ro
      - $HOME/.gitconfig:/root/.gitconfig:ro
      - $HOME/.gem/credentials:/root/.gem/credentials
